Repository SUSE/doc-caasp, pull requests merged in 2018-10, with the labels that each got.

#91 Add 'Pod Security Policies'
  xml/admin_security.xml
Labels: Merge

#98 Add Active Directory and openLDAP examples
  xml/admin_security.xml
Labels: Needs Review

#101 Change 'Configuring Remote Container Registry'
  xml/admin_administration.xml
Labels: On-Hold
