Repository SUSE/doc-caasp, pull requests merged in 2019-08, with the labels that each got.

#365 Align LDAP data structure
  adoc/admin-security-rbac.adoc
  adoc/deployment-bootstrap.adoc
Labels: Documentation

#381 [beta] Add terraform SCC and CPI information
  adoc/deployment-ecp.adoc
Labels: DeploymentGuide, v4

#299 Oidc docs
  images/src/png/velum_settings_oidc.png
  xml/admin_security.xml
Labels: AdminGuide, v3

#419 Add monitoring doc
  adoc/admin-centralized-logging.adoc
  adoc/admin-monitoring-health-checks.adoc
  adoc/admin-monitoring-stack.adoc
  adoc/admin-security-role-management.adoc
  adoc/book_admin.adoc
Labels: Documentation
