Repository SUSE/doc-caasp, pull requests merged in 2019-01, with the labels that each got.

#122 Minor fixes for package and ptf installations
  xml/admin_software.xml
Labels: Bug

#125 Add notes about changed NTP config with cloud-init
  xml/deployment_configuration.xml
Labels: Backport, Enhancement, v3, v4

#128 Add troubleshooting for node acceptance
  xml/admin_troubleshooting.xml
Labels: Backport, Merge, v3, v4

#132 Add note about cluster sizing reserves
  xml/deployment_sysreqs.xml
Labels: Backport, Enhancement, v3, v4
