Repository SUSE/doc-caasp, pull requests merged in 2019-04, with the labels that each got.

#185 Added quick install link for DAPS.
  README.adoc
Labels: Enhancement, Merge

#196 Errata for VMware
  adoc/deployment-bootstrap.adoc
  adoc/deployment-vmware.adoc
Labels: Merge

#197 Provide more information about ssh-agent
  adoc/deployment-bootstrap.adoc
Labels: DeploymentGuide, Merge, v4, vNext
