Repository SUSE/doc-caasp, pull requests merged in 2019-12, with the labels that each got.

#615 Fix indentation for configmap format example
  adoc/admin-security-ldap.adoc
Labels: AdminGuide, Bug

#606 Document 1.16.0 k8s
  adoc/admin-updates.adoc
  adoc/attributes.adoc
Labels: 4.1.0, On-Hold

#620 Fix kubelet-ca path
  adoc/admin-security-certificates.adoc
Labels: 4.0.3, AdminGuide, Enhancement

#625 Custom certificates for dex and gangway (Closes #619)
  adoc/admin-security-certificates.adoc
Labels: 4.1.0, AdminGuide

#638 Consolidate server certificate generation
  adoc/admin-monitoring-stack.adoc
  adoc/admin-security-certificates.adoc
  adoc/admin-software-installation.adoc
Labels: 4.1.0, AdminGuide

#642 Update certificate generation chapter
  adoc/admin-security-certificates.adoc
Labels: 4.1.0, AdminGuide
