Repository SUSE/doc-caasp, pull requests merged in 2019-10, with the labels that each got.

#529 Add addon upgrade plan instructions
  adoc/admin-updates.adoc
Labels: AdminGuide, Enhancement, v4

#530 Add HAProxy configuration
  adoc/deployment-loadbalancer.adoc
  adoc/deployment-preparation.adoc
Labels: DeploymentGuide, Enhancement, v4

#539 Extend debugging information
  adoc/admin-troubleshooting.adoc
Labels: AdminGuide, v4

#546 init external storage
  adoc/admin-ses-integration.adoc
  adoc/admin-software-installation.adoc
  adoc/book_admin.adoc
Labels: AdminGuide, On-Hold, P1, ReleaseNotes, v4

#551 Adapt upgrade instructions to make more sense
  adoc/admin-updates.adoc
Labels: AdminGuide, v4

#555 Add ETCD debug info
  adoc/admin-troubleshooting-etcd.adoc
  adoc/admin-troubleshooting.adoc
Labels: AdminGuide, v4

#560 Update airgapped deployment guide
  adoc/deployment-airgapped.adoc
Labels: DeploymentGuide, Enhancement, v4

#549 Add Instructions on Configuring Kubernetes Services
  adoc/deployment-bootstrap.adoc
Labels: DeploymentGuide, v4

#562 (bsc#1154404) fix 389ds ldif examples
  adoc/admin-security-ldap.adoc
Labels: AdminGuide, v4

#565 Release 4.0.1
  adoc/attributes.adoc
Labels: Overhead, P1, ReleaseNotes

#573 Add description of logs
  adoc/admin-troubleshooting-etcd.adoc
  adoc/admin-troubleshooting.adoc
Labels: AdminGuide, Enhancement, v4
