Repository SUSE/doc-caasp, pull requests merged in 2019-05, with the labels that each got.

#206 Describe Default PodSecurityPolicies
  adoc/admin-security-psp.adoc
  adoc/admin-security-rbac.adoc
  adoc/book_admin.adoc
  adoc/entities.adoc
Labels: AdminGuide, Needs Review, v4

#211 Feature/issue_145_adoc
  adoc/admin-flexvolume.adoc
Labels: Merge

#204 Architecture description
  DC-caasp-architecture
  adoc/architecture-description.adoc
  adoc/architecture-updates.adoc
  adoc/entities.adoc
  adoc/images/architecture-caasp-components.jpg
  adoc/images/logo_cilium.png
  adoc/images/logo_crio.svg
  adoc/images/logo_dex.png
  adoc/images/logo_etcd.svg
  adoc/images/logo_kubernetes.png
  adoc/images/logo_kured.png
Labels: On-Hold, v4

#217 Add Nutanix Acropolis to the Supported Environments chapter
  xml/deployment_sysreqs.xml
Labels: Enhancement, v3

#218 Add CRI-O proxy configuration to admin guide
  adoc/admin-crio-proxy.adoc
  adoc/book_admin.adoc
  adoc/entities.adoc
Labels: AdminGuide, v4

#226 Removed port 10255 from Network requirements
  xml/deployment_sysreqs.xml
Labels: DeploymentGuide, Enhancement, v3

#230 Vmware deployment
  adoc/deployment-sysreqs.adoc
  adoc/deployment-vmware.adoc
  adoc/entities.adoc
  adoc/images/vmware_step1.png
  adoc/images/vmware_step2.png
  adoc/images/vmware_step3.png
  adoc/images/vmware_step4.png
  adoc/images/vmware_step5.png
  adoc/images/vmware_step6.png
  adoc/images/vmware_step6b.png
Labels: DeploymentGuide, Needs Review, v4

#231 Update openstack documentation
  adoc/deployment-bootstrap.adoc
  adoc/deployment-ecp.adoc
Labels: DeploymentGuide, Needs Review, On-Hold, v4

#232 Polish updates for beta 2 deployment guide
  adoc/attributes.adoc
  adoc/book_deployment.adoc
  adoc/book_quickstart.adoc
  adoc/deployment-bootstrap.adoc
  adoc/deployment-ecp.adoc
  adoc/deployment-preparation.adoc
  adoc/deployment-sles.adoc
  adoc/deployment-sysreqs.adoc
  adoc/deployment-terraform-example.adoc
  adoc/deployment-vmware.adoc
  adoc/entities.adoc
  adoc/images/vmware_step6.png
Labels: DeploymentGuide, v4

#243 Rename caaspctl to skuba
  adoc/admin-security-psp.adoc
  adoc/architecture-description.adoc
  adoc/architecture-updates.adoc
  adoc/attributes.adoc
  adoc/deployment-bootstrap.adoc
  adoc/deployment-ecp.adoc
  adoc/deployment-loadbalancer.adoc
  adoc/deployment-preparation.adoc
  adoc/deployment-vmware.adoc
  adoc/entities.adoc
Labels: On-Hold, v4
