Repository SUSE/doc-caasp, pull requests merged in 2019-06, with the labels that each got.

#246 reboot management and cluster configuration
  adoc/admin-updates.adoc
  adoc/book_admin.adoc
  adoc/deployment-bootstrap.adoc
Labels: AdminGuide, v4

#222 Bare metal deployment guide
  adoc/book_deployment.adoc
  adoc/deployment-bare-metal.adoc
  adoc/deployment-loadbalancer.adoc
Labels: DeploymentGuide, v4

#265 Update terraform examples
  adoc/deployment-terraform-example.adoc
Labels: DeploymentGuide

#252 Add CRI-O registry configuration documentation
  adoc/admin-crio-proxy.adoc
  adoc/admin-crio-registries.adoc
  adoc/book_admin.adoc
Labels: AdminGuide, On-Hold, v4
