Repository SUSE/doc-caasp, pull requests merged in 2019-09, with the labels that each got.

#477 Admission Controller
  adoc/admin-security-access.adoc
  adoc/admin-security-admission.adoc
  adoc/admin-security-rbac.adoc
  adoc/book_admin.adoc
Labels: AdminGuide, v4

#522 Add clarification about multiple identities loaded into agent
  adoc/deployment-preparation.adoc
Labels: DeploymentGuide, Enhancement, v4

#526 Minor fix.
  adoc/admin-ses-integration.adoc
Labels: AdminGuide, Enhancement, v4
