Repository SUSE/doc-caasp, pull requests merged in 2019-07, with the labels that each got.

#291 Skip self-signed certificate verification for VMWare
  adoc/deployment-vmware.adoc
Labels: DeploymentGuide, Enhancement, v4

#301 Add more details about `internal_subnet` and `internal_router` options
  adoc/deployment-terraform-example.adoc
Labels: DeploymentGuide, v4

#340 Add docs for `skuba cluster upgrade plan`
  adoc/admin-updates.adoc
Labels: AdminGuide, On-Hold, v4

#303 Remove wrong description for worker
  adoc/deployment-terraform-example.adoc
Labels: DeploymentGuide, Enhancement, v4

#342 Remove kernel-default from openstack example
  adoc/deployment-terraform-example.adoc
Labels: DeploymentGuide, Enhancement, v4

#304 Add new chapter about troubleshooting
  adoc/admin-troubleshooting.adoc
  adoc/book_admin.adoc
Labels: AdminGuide, v4

#273 Add information about SSH key-based auth
  adoc/deployment-ecp.adoc
  adoc/deployment-terraform-example.adoc
Labels: DeploymentGuide, Enhancement, v4

#343 Add docs for skuba node upgrade plan
  adoc/admin-updates.adoc
Labels: AdminGuide, v4

#348 Add upgrade apply instructions
  adoc/admin-troubleshooting.adoc
  adoc/admin-updates.adoc
Labels: DeploymentGuide, On-Hold, v4

#355 Add RBAC and External LDAP documentation
  adoc/admin-security-ldap.adoc
  adoc/admin-security-rbac.adoc
  adoc/book_admin.adoc
  adoc/common_disclaimer.adoc
  adoc/common_glossary.adoc
  adoc/deployment-bootstrap.adoc
  adoc/images/oidc_flow.png
  adoc/images/rbac-configure-kubectl.png
  adoc/suse-rbac-oidc-flow.xml
Labels: AdminGuide, DeploymentGuide, v4

#347 Added RBAC ports to loadbalancer preparation
  adoc/deployment-preparation.adoc
  adoc/deployment-sysreqs.adoc
Labels: AdminGuide, On-Hold, v4

#354 Update airgap details
  xml/deployment_scenarios.xml
Labels: AdminGuide, Reported, v3

#356 Update requirements for 250 nodes + warning
  adoc/deployment-sysreqs.adoc
Labels: DeploymentGuide, Enhancement, v4

#266 AWS deployment documentation
  adoc/deployment-aws.adoc
  adoc/deployment-terraform-example.adoc
Labels: DeploymentGuide, Needs Review, v4
