Repository SUSE/doc-caasp, pull requests merged in 2019-11, with the labels that each got.

#583 Add missing steps for machine ID generation on manual VMWare deployment (bsc#1155322)
  adoc/deployment-vmware.adoc
Labels: Bug, DeploymentGuide, Reported, v4

#585 Add note about Crio proxy to deployment guides (bsc#1155323)
  adoc/admin-crio-proxy.adoc
  adoc/deployment-bare-metal.adoc
  adoc/deployment-bootstrap.adoc
  adoc/deployment-ecp.adoc
  adoc/deployment-vmware.adoc
Labels: DeploymentGuide, Enhancement, Reported, v4

#604 Unify use of placeholders (Closes #538, Closes #592).
  adoc/admin-cap-integration.adoc
  adoc/admin-centralized-logging.adoc
  adoc/admin-cluster-management.adoc
  adoc/admin-monitoring-health-checks.adoc
  adoc/admin-monitoring-stack.adoc
  adoc/admin-security-certificates.adoc
  adoc/admin-security-ldap.adoc
  adoc/admin-security-rbac.adoc
  adoc/admin-security-role-management.adoc
  adoc/admin-ses-integration.adoc
  adoc/admin-troubleshooting-etcd.adoc
  adoc/admin-troubleshooting.adoc
  adoc/admin-updates.adoc
  adoc/architecture-description.adoc
  adoc/architecture-updates.adoc
  adoc/common_intro_typography.adoc
  adoc/deployment-airgapped.adoc
  adoc/deployment-aws.adoc
  adoc/deployment-bootstrap.adoc
  adoc/deployment-ecp.adoc
  adoc/deployment-loadbalancer.adoc
  adoc/deployment-preparation.adoc
  adoc/deployment-sles.adoc
  adoc/deployment-terraform-example.adoc
  adoc/deployment-vmware.adoc
Labels: AdminGuide, DeploymentGuide, Enhancement, Overhead, QuickStartGuide, v4

#602 Kubelet cluster-wide root CA (bsc#1155810)
  adoc/admin-security-certificates.adoc
Labels: AdminGuide

#608 Add NTP server on management node note.
  adoc/deployment-sysreqs.adoc
Labels: 4.0.3, DeploymentGuide, v4

#609 Switch to SUSE Prometheus and Grafana helm charts
  adoc/admin-monitoring-stack.adoc
Labels: 4.0.3, AdminGuide, v4

#599 Add information about subnet sizing (Closes #593)
  adoc/deployment-sysreqs.adoc
Labels: DeploymentGuide, Enhancement, Reported, v4

#613 Increase Nginx config timeout value as HAProxy (bsc#1155597)
  adoc/deployment-loadbalancer.adoc
Labels: 4.0.3, DeploymentGuide, Enhancement, v4

#513 [wip] 389ds changes
  adoc/admin-security-ldap.adoc
  adoc/admin-security-rbac.adoc
  adoc/admin-security-user-group-management.adoc
Labels: 4.0.3, AdminGuide, Needs Review, On-Hold

#612 Secure helm tiller deployment with SSL/TLS (Closes #505)
  adoc/admin-cap-integration.adoc
  adoc/admin-software-installation.adoc
Labels: 4.0.3, AdminGuide, Enhancement, v4

#618 Mention other methods for exposing monitoring services
  adoc/admin-monitoring-stack.adoc
Labels: 4.0.3, AdminGuide

#614 Add PSP creation to prometheus config example
  xml/admin_monitoring.xml
Labels: AdminGuide, v3
