Repository SUSE/doc-caasp, pull requests merged in 2020-07, with the labels that each got.

#898 Add guide for monitoring NVIDIA GPUs
  adoc/admin-gpus.adoc
Labels: AdminGuide, v5

#900 Add note about vsphere cloud provider vCenter folder structure
  adoc/deployment-bootstrap.adoc
Labels: DeploymentGuide, Enhancement

#790 adoc: added list of changes from kubernetes 1.17. to 1.18
  adoc/admin-kubernetes-changes.adoc
  adoc/book_admin.adoc
Labels: 5.0

#907 Updating custom CA for OIDC in kube-apiserver, bsc#1173095
  adoc/admin-security-certificates.adoc
Labels: AdminGuide

#916 Cluster upgrade check documentation
  adoc/admin-updates.adoc
  adoc/deployment-airgapped.adoc
Labels: 5.0, AdminGuide

#909 Update kustomize links
  adoc/admin-security-rbac.adoc
  adoc/architecture-description.adoc
  adoc/deployment-bootstrap.adoc
Labels: 4.2.1, APJ squad, AdminGuide, ArchitectureGuide, DeploymentGuide, v5

#918 Correct kustomize dex example (#874)
  adoc/admin-security-ldap.adoc
  adoc/admin-security-rbac.adoc
  adoc/deployment-bootstrap.adoc
Labels: AdminGuide, DeploymentGuide, v5

#919 New command: skuba addon refresh localconfig
  adoc/admin-updates.adoc
Labels: AdminGuide, v5

#925 Doc how kubelet client certificate renew v4
  adoc/admin-security-certificates.adoc
Labels: 4.2.1

#920 Try to improve wording and make Helm 3 the preference (1607)
  adoc/admin-software-installation.adoc
Labels: v5

#912 Doc how kubelet client certificate renew v5
  adoc/admin-security-certificates.adoc
Labels: v5

#921 update version for 389ds v143 (#1775)
  adoc/admin-security-ldap.adoc
Labels: 5.0, APJ squad, AdminGuide

#908 Update admission controller info in GPU guide
  adoc/admin-gpus.adoc
Labels: AdminGuide, v5

#922 Add a cert-manager known issue
  adoc/admin-security-certificates.adoc
Labels: AdminGuide, v5

#928 Enhance hostname_from_dhcp description for vcp
  adoc/deployment-vmware.adoc
Labels: DeploymentGuide

#926 Add info to vmware tf deployment about new config
  adoc/deployment-terraform-example.adoc
Labels: 5.0, DeploymentGuide, Needs Review

#924 Add important note to etcd cluster restore
  adoc/admin-cluster-disaster-recovery-restore-master-nodes.adoc
Labels: AdminGuide

#881 Add support to forward K8s audit log to doc
  adoc/admin-centralized-logging.adoc
Labels: APJ squad, AdminGuide, ReleaseNotes

#930 Enable vSphere cloud provider on running cluster
  adoc/deployment-bootstrap.adoc
  adoc/deployment-vmware.adoc
Labels: DeploymentGuide

#923 Enhance skuba addon upgrade plan
  adoc/admin-updates.adoc
Labels: AdminGuide, v5

#935 Nginx ingress controller HA
  adoc/admin-security-nginx-ingress.adoc
Labels: 4.5, AdminGuide, Backport, v4

#913 Add information about using a bastion with skuba
  adoc/admin-updates.adoc
  adoc/deployment-bootstrap.adoc
  adoc/deployment-preparation.adoc
  adoc/deployment-sysreqs.adoc
Labels: AdminGuide, DeploymentGuide, Enhancement

#932 Use kubectl scale
  adoc/deployment-sysreqs.adoc
Labels: 4.5, Backport, DeploymentGuide, v4

#933 Individual and Wildcard certificate
  adoc/admin-monitoring-stack.adoc
Labels: 4.5, AdminGuide, Backport, v4

#929 update example for dex ad samaccountname (#832)
  adoc/admin-security-ldap.adoc
Labels: 4.5, AdminGuide

#941 Update attributes.adoc
  adoc/attributes.adoc
Labels: 5.0

#948 Switch suggested ssh key algorithm to ecdsa
  adoc/deployment-preparation.adoc
Labels: DeploymentGuide, v4, v5

#950 Fix typo on helm repo name
  adoc/admin-security-certificates.adoc
Labels: Bug
