Repository SUSE/doc-caasp, pull requests merged in 2020-01, with the labels that each got.

#647 Security Recommendations
  adoc/admin-security-firewall.adoc
  adoc/admin-security-role-management.adoc
  adoc/book_admin.adoc
  adoc/deployment-sysreqs.adoc
Labels: 4.1.0, AdminGuide, v4

#650 Add section about requirements for cluster update (Closes #645)
  adoc/admin-updates.adoc
Labels: 4.1.0, AdminGuide

#617 Add note to address fix of Dex/Gangway replica off-balanced issue (bsc#1157337)
  adoc/deployment-sysreqs.adoc
Labels: DeploymentGuide

#655 V3 security recommendations
  xml/admin_security.xml
  xml/deployment_sysreqs.xml
Labels: AdminGuide, Backport, Enhancement, v3

#629 [WIP] Add documentation for the ability to set the datastore_cluster vmware/TF
  adoc/deployment-terraform-example.adoc
Labels: 4.1.1, DeploymentGuide, Enhancement, On-Hold

#634 Update Cilium documentation introduction
  adoc/deployment-cilium.adoc
Labels: 4.1.1, DeploymentGuide, On-Hold

#661 Admin guide: add Stratos instructions
  adoc/admin-stratos-web-console.adoc
  adoc/book_admin.adoc
  adoc/common_tech_preview.adoc
Labels: 4.1.0, AdminGuide, ReleaseNotes, v4

#635 Report the current installed caasp version (bsc#1157323)
  adoc/architecture-updates.adoc
  adoc/deployment-bootstrap.adoc
Labels: 4.1.1, ArchitectureGuide, DeploymentGuide

#641 Fix loglevel example in troubleshooting to 5
  adoc/admin-troubleshooting.adoc
Labels: 4.1.1, AdminGuide, On-Hold

#678 Add etcd performance storage tests (Closes #657)
  adoc/deployment-sysreqs.adoc
Labels: 4.1.1, DeploymentGuide, Enhancement, v4

#687 Add documentation on how to manually update a node (Closes #652)
  adoc/admin-updates.adoc
Labels: 4.1.1, AdminGuide, Enhancement, On-Hold, Reported, X squad, v4

#675 Reword k8s and addon upgrade instructions (Closes #664, Closes #667, Closes #643)
  adoc/admin-updates.adoc
Labels: 4.1.1, Bug, DeploymentGuide, Reported, v4

#693 Revert "fixes bsc#1157337"
  adoc/deployment-sysreqs.adoc
Labels: On-Hold, v4

#679 Switch cri-o to system proxy configuration
  adoc/admin-crio-proxy.adoc
  adoc/deployment-bare-metal.adoc
  adoc/deployment-ecp.adoc
  adoc/deployment-preparation.adoc
  adoc/deployment-vmware.adoc
Labels: 4.1.1, AdminGuide, Needs Review
