Repository SUSE/doc-caasp, pull requests merged in 2020-11, with the labels that each got.

#1043 fix warning message for rsyslog segfault [bsc#1155969]
  adoc/admin-logging-centralized.adoc
Labels: 4.2.4, 4.5.2, AdminGuide, Backport

#1042 Add missing part on manually renew the metrics-server cert
  adoc/admin-security-certificates.adoc
Labels: AdminGuide, Backport

#1044 Update Kubernetes and etcd version for CaaSP v4.2.4
  adoc/admin-logging-centralized.adoc
  adoc/admin-velero-deployment.adoc
  adoc/attributes.adoc
Labels: 4.2.4

#804 add documents for azure terraform (#1496)
  adoc/book_deployment.adoc
  adoc/deployment-azure.adoc
  adoc/deployment-terraform-example.adoc
  adoc/entities.adoc
Labels: 4.5.2, APJ squad, DeploymentGuide, ReleaseNotes

#878 Add Azure cloud provider support document
  adoc/admin-storage-azure.adoc
  adoc/admin-storage-vsphere.adoc
  adoc/book_admin.adoc
  adoc/deployment-bootstrap.adoc
  adoc/deployment-sysreqs.adoc
Labels: 4.5.2, AdminGuide, DeploymentGuide, On-Hold, ReleaseNotes

#1045 Add cpi_enable to azure deployment
  adoc/deployment-azure.adoc
Labels: DeploymentGuide

#1049 Add instruction on how to create the kubelet server certificate/key
  adoc/admin-security-certificates.adoc
Labels: 4.2.5, 4.5.2, Backport
