Repository SUSE/doc-caasp, pull requests merged in 2020-08, with the labels that each got.

#934 Configures subpath by helm chart values
  adoc/admin-monitoring-stack.adoc
Labels: 4.5, AdminGuide, Backport, v4

#951 Aligns container registry to v4.5
  adoc/admin-centralized-logging.adoc
  adoc/admin-security-ldap.adoc
  adoc/admin-software-installation.adoc
  adoc/admin-velero-deployment.adoc
  adoc/deployment-airgapped.adoc
Labels: 4.5.0

#957 Add detail for Helm and Tiller installation (#633)
  adoc/deployment-airgapped.adoc
Labels: 4.2.2, 4.5.0, DeploymentGuide

#960 Fix wording for module oddity
  adoc/book_deployment.adoc
  adoc/deployment-vmware.adoc
Labels: 4.5.0, DeploymentGuide

#952 Added a logging section
  adoc/admin-logging-audit.adoc
  adoc/admin-logging-centralized.adoc
  adoc/admin-logging-skuba.adoc
  adoc/admin-logging.adoc
  adoc/admin-troubleshooting.adoc
  adoc/book_admin.adoc
  adoc/book_deployment.adoc
  adoc/deployment-bootstrap.adoc
Labels: 4.5.x, AdminGuide, Backport, DeploymentGuide, Enhancement, v4

#962 fix product setup
  adoc/deployment-bare-metal-or-kvm.adoc
  adoc/deployment-bootstrap.adoc
  adoc/deployment-loadbalancer.adoc
  adoc/deployment-preparation.adoc
  adoc/deployment-sles.adoc
  adoc/deployment-vmware.adoc
Labels: 4.5.0

#959 adoc: reflect cordon & drain operations on update
  adoc/admin-updates.adoc
Labels: 4.5.0, AdminGuide, Enhancement, v4

#964 Fix references/links to base os version (Closes #963)
  adoc/admin-crio-proxy.adoc
  adoc/admin-troubleshooting.adoc
  adoc/architecture-updates.adoc
  adoc/attributes.adoc
  adoc/deployment-bare-metal-or-kvm.adoc
  adoc/deployment-bootstrap.adoc
  adoc/deployment-loadbalancer.adoc
  adoc/deployment-vmware.adoc
Labels: 4.5.0

#977 Fix CaaSP version in Helm 2 to 3 Migration section
  adoc/admin-software-installation.adoc
Labels: 4.5.0, AdminGuide, Bug

#971 Add LDAP in system requirement and Update RBAC doc structure
  adoc/admin-security-access.adoc
  adoc/admin-security-configure-authentication-connector.adoc
  adoc/admin-security-deploy-ldap-server.adoc
  adoc/admin-security-ldap-user-group-management.adoc
  adoc/admin-security-ldap.adoc
  adoc/admin-security-rbac-administration.adoc
  adoc/admin-security-rbac-user-access.adoc
  adoc/admin-security-rbac.adoc
  adoc/book_admin.adoc
  adoc/deployment-sysreqs.adoc
Labels: 4.5.0, Enhancement
