Repository SUSE/doc-caasp, pull requests merged in 2020-04, with the labels that each got.

#745 Add suggestions for adding posix group in organizational unit (Closes #742)
  adoc/admin-security-user-group-management.adoc
Labels: AdminGuide, v4

#682 Create document for master nodes disaster recovery
  adoc/admin-dr-backup-etcd.adoc
  adoc/admin-dr-deployment-on-aws.adoc
  adoc/admin-dr-deployment-on-premise.adoc
  adoc/admin-dr-restore-master-nodes.adoc
Labels: AdminGuide, Blocked, On-Hold, ReleaseNotes, taiwansquad, v4

#767 Added a list of addons-image info
  adoc/deployment-airgapped.adoc
Labels: 4.2.0, DeploymentGuide

#724 Update kured version
  adoc/attributes.adoc
Labels: 4.2.0, AdminGuide, ArchitectureGuide, DeploymentGuide, ReleaseNotes, v4

#694 Apply temporarily reverted replicas management to deployment reqs
  adoc/deployment-bare-metal-or-kvm.adoc
  adoc/deployment-loadbalancer.adoc
  adoc/deployment-sysreqs.adoc
Labels: 4.2.0, DeploymentGuide, v4

#777 Rework quickstart to use bare metal/KVM (Closes #776)
  adoc/book_deployment.adoc
  adoc/book_quickstart.adoc
  adoc/deployment-bare-metal-or-kvm.adoc
Labels: 4.2.0, QuickStartGuide

#779 Warning about rsyslog running on machine and cluster
  adoc/admin-centralized-logging.adoc
Labels: 4.2.0, AdminGuide, Enhancement, v4

#762 Add Prometheus recording rules example
  adoc/admin-monitoring-stack.adoc
Labels: AdminGuide, v4

#760 Openssh note
  adoc/deployment-preparation.adoc
Labels: DeploymentGuide, v4

#782 Add documents for manual creation of AWS role instance policy and profile (Closes #772)
  adoc/admin-troubleshooting.adoc
  adoc/deployment-aws.adoc
Labels: DeploymentGuide, Needs Review, v4

#765 Monitor certificate status
  adoc/admin-monitoring-stack.adoc
  adoc/admin-security-certificates.adoc
Labels: AdminGuide, taiwansquad, v4

#786 Fix velero command typo
  adoc/admin-dr-deployment-on-aws.adoc
  adoc/admin-dr-deployment-on-premise.adoc
Labels: P1
