Repository SUSE/doc-caasp, pull requests merged in 2020-02, with the labels that each got.

#697 Fix typo
  adoc/admin-ses-integration.adoc
Labels: 4.1.1, AdminGuide, Bug, v4

#695 Amend airgap documentation with corrections for registries.conf (Closes #668, Closes #685)
  adoc/deployment-airgapped.adoc
  adoc/deployment-bare-metal.adoc
  adoc/deployment-bootstrap.adoc
  adoc/deployment-ecp.adoc
  adoc/deployment-vmware.adoc
Labels: 4.1.2, Blocked, DeploymentGuide, v4

#718 Architecture description: reword fault tolerant section
  adoc/architecture-description.adoc
Labels: ArchitectureGuide
