Repository SUSE/doc-caasp, pull requests merged in 2020-09, with the labels that each got.

#982 Kubelet config mod (bsc#1174219)
  adoc/admin-configure-kubelet.adoc
  adoc/admin-flexvolume.adoc
  adoc/book_admin.adoc
Labels: 4.5.0, AdminGuide, Backport, Bug

#979 A guide for migration to CaaSP 4.5
  adoc/admin-migrate-caasp4.5.adoc
Labels: 4.5.0, AdminGuide, EngineeringInput, ReleaseNotes

#986 Enable Jumbo Frames for VMware deployment (bsc#1175490)
  adoc/deployment-vmware.adoc
Labels: 4.5.0, Backport, DeploymentGuide, ReleaseNotes

#984 My cluster
  adoc/admin-monitoring-stack.adoc
  adoc/admin-security-certificates.adoc
  adoc/admin-security-configure-authentication-connector.adoc
  adoc/admin-security-rbac-user-access.adoc
  adoc/admin-storage-vsphere.adoc
  adoc/admin-troubleshooting.adoc
  adoc/architecture-description.adoc
  adoc/deployment-bootstrap.adoc
Labels: 4.5.x

#990 Add new file for custom configuration
  adoc/admin-crio-registries.adoc
  adoc/admin-custom-config.adoc
  adoc/admin-security-configure-authentication-connector.adoc
  adoc/admin-security-psp.adoc
Labels: 4.5.x, AdminGuide, ReleaseNotes

#1000 Add instruction on how to fix invalid client secret (bsc#1173055)
  adoc/admin-troubleshooting.adoc
Labels: 4.5.1, AdminGuide

#998 Add kubelet.conf warning message for k8s version < 1.17 (bsc#1176578)
  adoc/admin-security-certificates.adoc
Labels: 4.5.1, 4.5.x, AdminGuide, Backport

#955 Day 1 operation to replace OIDC server CA
  adoc/admin-security-certificates.adoc
Labels: 4.5.x, AdminGuide
