Repository SUSE/doc-caasp, pull requests merged in 2020-05, with the labels that each got.

#784 Clarify usage of users and OIDC token refresh (Closes #753)
  adoc/admin-security-rbac.adoc
Labels: AdminGuide, Enhancement, On-Hold, taiwansquad, v4

#785 admin-updates: Update information for 1.6 update
  adoc/admin-updates.adoc
Labels: 4.2.1, Needs Review, On-Hold, v4

#783 Update deployment-cilium.adoc for Cilium 1.6
  adoc/admin-cilium.adoc
  adoc/deployment-cilium.adoc
Labels: 4.2.1, DeploymentGuide, On-Hold, networking, v4

#791 Disaster Recovery Chapter Reorganization
  adoc/admin-cluster-disaster-recovery-backup.adoc
  adoc/admin-cluster-disaster-recovery-restore-master-nodes.adoc
  adoc/admin-cluster-disaster-recovery.adoc
  adoc/admin-velero-backup.adoc
  adoc/admin-velero-deployment-on-aws.adoc
  adoc/admin-velero-deployment-on-premise.adoc
  adoc/admin-velero-disaster-recovery.adoc
  adoc/admin-velero-prereqs.adoc
  adoc/admin-velero-restore.adoc
  adoc/admin-velero-usecase.adoc
  adoc/book_admin.adoc
Labels: AdminGuide, taiwansquad, v4

#781 Update cilium documentation for 1.6 update
  adoc/architecture-description.adoc
  adoc/attributes.adoc
  make_release_package.sh
Labels: 4.2.1, ArchitectureGuide, Blocked, Needs Review, On-Hold, Style, networking, v4

#770 Add networking whitelist to deployment requirements (Closes #600)
  adoc/deployment-sysreqs.adoc
Labels: DeploymentGuide, Needs Review, v4

#803 Add etcd cluster backup intro
  adoc/admin-cluster-disaster-recovery-backup.adoc
  adoc/admin-cluster-disaster-recovery.adoc
  adoc/book_admin.adoc
Labels: 4.2.1, AdminGuide, Enhancement

#780 Add Audit Log chapter (Closes #318, Closes #310)
  adoc/admin-audit.adoc
  adoc/book_admin.adoc
Labels: 4.2.1, AdminGuide, v4

#796 add information about disk formats for vmware
  adoc/deployment-vmware.adoc
Labels: 4.2.1, DeploymentGuide

#797 Enhance terraform vsphere_resource_pool details
  adoc/deployment-terraform-example.adoc
Labels: 4.2.1, DeploymentGuide, Enhancement, taiwansquad

#787 Add instructions for monitoring of certificate status (#765)
  adoc/admin-monitoring-stack.adoc
  adoc/admin-security-certificates.adoc
Labels: 4.2.1, AdminGuide, On-Hold, v4

#768 Add vSphere cloud provider support document
  adoc/admin-software-installation.adoc
  adoc/admin-storage-vsphere.adoc
  adoc/admin-troubleshooting.adoc
  adoc/book_admin.adoc
  adoc/deployment-bootstrap.adoc
  adoc/deployment-vmware.adoc
Labels: 4.2.1, AdminGuide, DeploymentGuide, On-Hold, ReleaseNotes, v4

#738 Add horizontal pod autoscaler in monitoring chapter
  adoc/admin-monitoring-horizontal-pod-autoscaler.adoc
  adoc/book_admin.adoc
  adoc/deployment-bootstrap.adoc
Labels: 4.2.1, AdminGuide, v4

#793 Cilium docs updates 1.6 (Closes #778)
  adoc/admin-cilium.adoc
  adoc/admin-updates.adoc
  adoc/architecture-description.adoc
  adoc/deployment-cilium.adoc
Labels: 4.2.1, On-Hold, networking

#809 Fix numbered list and indentation
  adoc/deployment-vmware.adoc
Labels: DeploymentGuide, Style

#846 Remove one character
  LICENSE
  README.adoc
  adoc/admin-centralized-logging.adoc
  adoc/admin-monitoring-stack.adoc
  adoc/admin-security-certificates.adoc
  adoc/admin-security-psp.adoc
  adoc/admin-software-installation.adoc
  adoc/admin-updates.adoc
  adoc/admin-velero-prereqs.adoc
  adoc/attributes.adoc
  adoc/common_glossary.adoc
  adoc/deployment-sysreqs.adoc
Labels: Needs Review

#850 Better wording for PSP
  adoc/admin-security-psp.adoc
Labels: Needs Review

#856 fix suggestion for vspshere configuration (#1618)
  adoc/deployment-bootstrap.adoc
Labels: 4.2.1
