Repository SUSE/doc-caasp, pull requests merged in 2020-03, with the labels that each got.

#689 Update deployment guide to support KVM
  adoc/.deployment-sysreqs.adoc.swp
  adoc/architecture-description.adoc
  adoc/attributes.adoc
  adoc/book_deployment.adoc
  adoc/common_disclaimer.adoc
  adoc/deployment-bare-metal-or-kvm.adoc
  adoc/deployment-preparation.adoc
  adoc/deployment-sles.adoc
  adoc/deployment-sysreqs.adoc
Labels: DeploymentGuide, Enhancement, On-Hold, PO/PM, ReleaseNotes, v4

#731 Fix kubernetes node health check
  adoc/admin-monitoring-stack.adoc
Labels: AdminGuide, Bug, v4

#736 Clarify certificate rotation process
  adoc/admin-security-certificates.adoc
  adoc/architecture-description.adoc
  adoc/deployment-bootstrap.adoc
Labels: 4.1.2, AdminGuide, Enhancement, v4

#737 Warning about multiples kubeconfig with the same user
  adoc/admin-security-rbac.adoc
  adoc/admin-security-user-group-management.adoc
Labels: 4.2.0, AdminGuide, v4

#719 [WIP] Add more terms to the glossary
  adoc/common_glossary.adoc
  adoc/entities.adoc
Labels: Enhancement, On-Hold, Overhead

#740 Update archi diagram (Closes #734)
  adoc/architecture-description.adoc
  adoc/book_deployment.adoc
  adoc/deployment-default.adoc
  adoc/deployment-sysreqs.adoc
  adoc/images/architecture-caasp-components.jpg
  adoc/images/caasp_cluster_components.png
  adoc/images/caasp_cluster_software.png
  adoc/images/src/caasp_cluser_airgap_network.drawio
  adoc/images/src/caasp_cluster_airgap.drawio
  adoc/images/src/caasp_cluster_components.drawio
  adoc/images/src/caasp_cluster_software.drawio
Labels: AdminGuide, ArchitectureGuide, DeploymentGuide, On-Hold, v4

#732 Document addons customization
  adoc/admin-security-ldap.adoc
  adoc/admin-security-psp.adoc
  adoc/admin-security-rbac.adoc
  adoc/architecture-description.adoc
  adoc/deployment-bootstrap.adoc
Labels: 4.2.0, AdminGuide, ArchitectureGuide, DeploymentGuide, v4

#744 add suggestions for binding group to role (#741)
  adoc/admin-security-role-management.adoc
Labels: AdminGuide, v4

#722 add vmware info about a new var
  adoc/deployment-terraform-example.adoc
Labels: 4.2.0, DeploymentGuide, v4

#729 Add Disaster recovery
  adoc/admin-disaster-recovery.adoc
  adoc/admin-dr-backup.adoc
  adoc/admin-dr-deployment-on-aws.adoc
  adoc/admin-dr-deployment-on-premise.adoc
  adoc/admin-dr-prereqs.adoc
  adoc/admin-dr-restore.adoc
  adoc/admin-dr-usecase.adoc
  adoc/book_admin.adoc
  adoc/deployment-aws.adoc
Labels: 4.2.1
