Repository SUSE/doc-caasp, pull requests merged in 2020-10, with the labels that each got.

#1025 Backport kucero to caasp4
  adoc/admin-security-certificates.adoc
Labels: 4.2.4, AdminGuide

#1018 Monitor cilium client secret (bsc#1176904)
  adoc/admin-security-certificates.adoc
Labels: 4.2.4, 4.5.2, AdminGuide, Backport

#1024 Add instruction on how to auto rotate cilium etcd client cert (bsc#1176904)
  adoc/admin-security-certificates.adoc
Labels: 4.2.4, 4.5.2, AdminGuide, Backport

#1016 Monitor all certificates with suffix *.crt and *.pem
  adoc/admin-security-certificates.adoc
Labels: 4.2.4, 4.5.2, AdminGuide, Backport

#1015 Update chapter structure
  adoc/admin-security-certificates.adoc
Labels: 4.5.2, AdminGuide

#1029 Update attributes.adoc
  adoc/attributes.adoc
Labels: 4.5.1

#1003 Adds documentation on cluster shutdown and startup
  adoc/admin-shutdown-startup.adoc
  adoc/book_admin.adoc
Labels: 4.5.x, AdminGuide, Documentation

#1033 Adds namespace to helm commands
  adoc/admin-logging-centralized.adoc
Labels: 4.5.x, Bug

#1002 Kucero signs kubelet server csr
  adoc/admin-security-certificates.adoc
Labels: 4.5.2, AdminGuide

#1036 Fix typo on restart oidc-gangway
  adoc/admin-velero-usecase.adoc
Labels: 4.5.x, Backport

#981 Support Velero 1.4
  adoc/admin-velero-backup.adoc
  adoc/admin-velero-deployment.adoc
  adoc/admin-velero-disaster-recovery.adoc
  adoc/admin-velero-prereqs.adoc
  adoc/admin-velero-restore.adoc
  adoc/admin-velero-usecase.adoc
Labels: 4.5.2, AdminGuide

#1010 Create Ceph user inplace of default client.admin
  adoc/admin-ses-integration.adoc
Labels: 4.5.2, AdminGuide

#974 VCP CPI enabled will disable hostname from DHCP
  adoc/deployment-vmware.adoc
Labels: 4.5.2, DeploymentGuide
