Repository SUSE/doc-caasp, pull requests merged in 2020-06, with the labels that each got.

#854 Fix typo
  adoc/admin-monitoring-stack.adoc
Labels: Needs Review

#855 Add extraScrapeConfigs in prometheus-config-values.yaml
  adoc/admin-monitoring-stack.adoc
Labels: Needs Review

#806 Remove reference to crio.conf
  adoc/admin-troubleshooting.adoc
Labels: 5.0, On-Hold

#845 Better wording for self-signed certificate
  adoc/admin-security-certificates.adoc
Labels: 4.2.1, AdminGuide, Bug, Needs Review

#848 Backup addon certs in admin node
  adoc/admin-security-certificates.adoc
Labels: Needs Review

#853 Generates new etcd client certs for monitoring
  adoc/admin-monitoring-stack.adoc
Labels: Needs Review

#868 Change Kubernetes etcd cronjob example to backup daily at 1am
  adoc/admin-cluster-disaster-recovery-backup.adoc
Labels: AdminGuide

#872 Update component version numbers for release 4.2.1
  adoc/attributes.adoc
  adoc/docinfo.xml
Labels: Overhead

#875 Require disk.EnableUUID for vsphere deployment
  adoc/deployment-bootstrap.adoc
Labels: DeploymentGuide

#887 Fix apiserver-etcd-client parent CA
  adoc/admin-security-certificates.adoc
Labels: 4.2.1, 5.0, AdminGuide, Needs Review

#882 Describe metrics-server certifícate is skuba-managed certificate
  adoc/admin-security-certificates.adoc
Labels: 4.2.1

#891 Backport fixes for #826
  adoc/common_glossary.adoc
  adoc/deployment-bare-metal-or-kvm.adoc
  adoc/deployment-loadbalancer.adoc
Labels: Backport, DeploymentGuide, Overhead

#866 Remove idprefix
  adoc/admin-centralized-logging.adoc
  adoc/admin-cluster-disaster-recovery.adoc
  adoc/admin-cluster-management.adoc
  adoc/admin-monitoring-stack.adoc
  adoc/admin-security-admission.adoc
  adoc/admin-security-certificates.adoc
  adoc/admin-security-ldap.adoc
  adoc/admin-security-nginx-ingress.adoc
  adoc/admin-security-rbac.adoc
  adoc/admin-security-role-management.adoc
  adoc/admin-security-user-group-management.adoc
  adoc/admin-ses-integration.adoc
  adoc/admin-software-installation.adoc
  adoc/admin-troubleshooting-etcd.adoc
  adoc/admin-troubleshooting.adoc
  adoc/admin-updates.adoc
  adoc/admin-velero-prereqs.adoc
  adoc/common_legal.adoc
  adoc/deployment-airgapped.adoc
  adoc/deployment-aws.adoc
  adoc/deployment-bare-metal-or-kvm.adoc
  adoc/deployment-bootstrap.adoc
  adoc/deployment-loadbalancer.adoc
  adoc/deployment-openstack.adoc
  adoc/deployment-preparation.adoc
  adoc/deployment-sles.adoc
  adoc/deployment-sysreqs.adoc
  adoc/deployment-terraform-example.adoc
  adoc/deployment-vmware.adoc
Labels: 5.0, AdminGuide, ArchitectureGuide, DeploymentGuide, Needs Review, ReleaseNotes, Style, v5

#888 Add note that if labels already existed
  adoc/admin-security-certificates.adoc
Labels: 4.2.1, AdminGuide, Needs Review

#879 Add kubernete control plane certificate auto rotation
  adoc/admin-security-certificates.adoc
  adoc/deployment-vmware.adoc
Labels: AdminGuide, v5

#877 Add admin doc for GPUs
  adoc/admin-gpus.adoc
  adoc/book_admin.adoc
  adoc/entities.adoc
Labels: 5.0, AdminGuide

#874 Correct kustomize dex example
  adoc/admin-security-ldap.adoc
  adoc/admin-security-rbac.adoc
  adoc/deployment-bootstrap.adoc
Labels: 4.2.1, 5.0, AdminGuide, Backport, DeploymentGuide, Needs Review

#873 Better wording for Velero chapter
  adoc/admin-velero-backup.adoc
  adoc/admin-velero-deployment-on-aws.adoc
  adoc/admin-velero-deployment.adoc
  adoc/admin-velero-disaster-recovery.adoc
  adoc/admin-velero-prereqs.adoc
  adoc/admin-velero-restore.adoc
  adoc/admin-velero-usecase.adoc
Labels: 4.2.1, 5.0, AdminGuide, Backport, Needs Review

#867 AutoYaST adapted for CaaSP 5 based on SLE-15-SP2
  adoc/deployment-bare-metal-or-kvm.adoc
Labels: 5.0, DeploymentGuide, v5

#893 Add note about helm-mirror in airgap (1607)
  adoc/deployment-airgapped.adoc
Labels: 4.2.1, DeploymentGuide, v5

#897 Bump dex version to 2.23.0
  adoc/admin-security-rbac.adoc
  adoc/attributes.adoc
  adoc/deployment-bootstrap.adoc
Labels: v5

#899 Add troubleshoots on invalid client credentials
  adoc/admin-troubleshooting.adoc
Labels: 4.2.0, 4.2.1, AdminGuide

#896 Add information for Helm 3 and 2to3 migration (1607)
  adoc/admin-centralized-logging.adoc
  adoc/admin-monitoring-stack.adoc
  adoc/admin-security-certificates.adoc
  adoc/admin-security-nginx-ingress.adoc
  adoc/admin-software-installation.adoc
  adoc/admin-stratos-web-console.adoc
  adoc/admin-velero-deployment-on-aws.adoc
  adoc/admin-velero-deployment.adoc
  adoc/admin-velero-disaster-recovery.adoc
Labels: v5

#906 Minor typos and path fix
  adoc/deployment-preparation.adoc
Labels: DeploymentGuide, v5

#904 Add warning about ssh-agent
  adoc/deployment-preparation.adoc
  adoc/deployment-vmware.adoc
Labels: DeploymentGuide, v4, v5
